#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../library/source/HC_12.cpp ../library/source/neopixel.cpp ../library/source/neopixel_uno.cpp

# header files in this project
HEADERS := ../library/headers/HC_12.hpp ../library/headers/HC_12_uno.hpp ../library/headers/neopixel_uno.hpp ../library/headers/GRB_decorator.hpp ../library/headers/helpmath.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.uno
