#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := 

# header files in this project
HEADERS := ../library/headers/neopixel.hpp ../library/headers/HC-SR04.hpp ../library/headers/neopixel_due.hpp ../library/headers/helpmath.hpp ../library/headers/HC_12.hpp ../library/headers/HC_12_due.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
